package com.example.rzob21.utilits

var APP_CALENDAR_DATE = ""
var APP_CALENDAR_DATE_DAY = 0
var APP_CALENDAR_DATE_MONTH = 0
var APP_CALENDAR_DATE_YEAR = 0
var APP_DATE_TODAY = ""
var APP_DATE_TODAY_DAY = 0
var APP_DATE_PICK_MONTH_L = ""
var APP_DATE_TODAY_YEAR = 0
var APP_CALENDAR_DATE_MONTH_CHECK = 0
var APP_CALENDAR_DATE_YEAR_CHECK = 0